replicaCount: 1

image:
  repository: <container image url>
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1


