apiVersion: v1
kind: Template
labels:
  app: nist-data-mirror
objects:
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: nist-data-mirror
    namespace: ${NAMESPACE}
    labels:
      app: nist-data-mirror
      app.kubernetes.io/component: nist-data-mirror
      app.kubernetes.io/instance: nist-data-mirror
      app.kubernetes.io/part-of: nist-data-mirror
    annotations:
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: 'https://github.com/ranser102/nist-data-mirror.git'
  spec:
    nodeSelector: null
    output:
      to:
        kind: DockerImage
        name: ${TARGET_EXTERNAL_REGISTRY}/${TARGET_IMAGE_STREAM}:${TARGET_IMAGE_STREAM_TAG}
      pushSecret:
        name: docker-repo-secret
    resources: {}
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    strategy:
      type: Docker
      dockerStrategy:
        env:
          - name: sleeptime
            value: ${SLEEPTIME}
        dockerfilePath: Dockerfile
    postCommit: {}
    source:
      type: Git
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: /
    triggers:
      - type: ConfigChange
      - type: ImageChange
    runPolicy: Serial
parameters:
- description: The namespace to deploy into
  name: NAMESPACE
  required: true
- description: The sleep time between each download
  name: SLEEPTIME
  required: true
- description: The name of the image we are creating
  name: TARGET_IMAGE_STREAM
  value: nist-data-mirror
  required: true
- description: The tag of the image we are creating
  name: TARGET_IMAGE_STREAM_TAG
  value: "0.2"
  required: true
- description: The external docker images registry
  name: TARGET_EXTERNAL_REGISTRY
  value: <container image repository>  
- description: Git source URI
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/ranser102/nist-data-mirror.git
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: master
  required: true
    